CREATE PROCEDURE [dbo].[GetDatabaseRowVersion]
AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	SET NOCOUNT ON
	--Changed 10/16/2024
	SELECT dbts = (CONVERT(BIGINT,MIN_ACTIVE_ROWVERSION())-1);
END
GO